#!/bin/bash

#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=8:mem=120gb:scratch_local=45gb
#PBS -N metilene_output
#PBS -j oe

# Author: Iris Sammarco
# Date: 03/2025
#
# Purpose:
# Automate running metilene DMR calling on prepared unionbed input files and filtering results by q-value < 0.05
#
# Inputs:
# - Directory with metilene input unionbed files (*_union.bed), generated by previous steps.
#   These files have columns: chrom, pos, group1_replicate1, group1_rep2, ... group2_rep3, and contain proportion of methylated reads at a specific genomic position
#   Example:
#	chrom   pos     LC_1    LC_2    LC_3    LD_1    LD_2    LD_3
#	NC_008334.1     24     0.00    0.00     -     0.01    0.00    0.00
#	NC_008334.1     26     0.19    0.14    0.09    0.08    0.03    0.12
#
# Outputs:
# - Raw metilene output files in BED format with DMRs for each comparison/context
# - Filtered DMR BED files containing only DMRs with q-value < 0.05
#
# Requirements:
# - Metilene installed and accessible in PATH
# - Perl metilene_output.pl script available (path customizable below)
# - Adjust paths below for your environment
#
# Usage:
#   qsub 3_run_metilene_and_filter.sh

# --- User customizable variables ---

input_dir="/path/to/dmrs/metilene_input"            # Input: unionbed files from previous step
output_dir="/path/to/dmrs/metilene_output"           # Output: raw DMR results
filtered_dir="/path/to/dmrs/metilene_output_qval_0.05" # Output: filtered DMRs with q < 0.05
mkdir -p "$output_dir" "$filtered_dir"

# Path to the Perl filtering script provided with Metilene (change this to your installed location)
metilene_filter_script="~/.conda/envs/metilene/bin/metilene_output.pl"

# Number of threads to use for Metilene (adjust if needed)
metilene_threads=4

# --- Step 1: Run Metilene on all unionbed files ---

for file in "$input_dir"/*_union.bed; do
    filename=$(basename "$file") # Extract the filename without path
    prefix="${filename%_union.bed}" # Extract the prefix (e.g., CpG_LC_LD from CpG_LC_LD_union.bed)

    # Extract group names from filename convention
    group1=$(echo "$prefix" | cut -d'_' -f2)
    group2=$(echo "$prefix" | cut -d'_' -f3)
	
	# Define output file
    output_file="${output_dir}/${prefix}_dmr.bed" 
	
	# Run metilene with default parameters
    echo "Running metilene on $filename comparing $group1 vs $group2"
    metilene -t $metilene_threads -a "$group1" -b "$group2" "$file" | \
        sort -k1,1V -k2,2n > "$output_file"

    echo "Metilene output saved to $output_file"
done

# --- Step 2: Filter Metilene output files by q-value < 0.05 ---

mkdir -p "$filtered_dir"

for bed_file in "$output_dir"/*.bed; do

    # Get the base name of the bed file (without the path)
    base_name=$(basename "$bed_file" .bed)
    
	# Define the output file name based on the input file
	output_file2="${filtered_dir}/${base_name}_qval_0.05.bed"
    
    echo "Filtering $bed_file by q-value < 0.05"
	# Run the Perl script with the input and output files
    perl "$metilene_filter_script" -q "$bed_file" -o "$output_file2" -p 0.05

    echo "Filtered output saved to $output_file2"
done
